-- HQ 파일럿 사용현황: 접속·활동 로그 (2026-06-17)
-- Supabase SQL Editor에서 수동 실행. 신규 테이블 1개만 추가(기존 무손상).

create table if not exists public.usage_logs (
  id          bigint generated by default as identity primary key,
  event_type  text not null,              -- 'login' | 'edit'
  area        text,                         -- 'roster' | 'vehicles' | null
  campus_id   uuid,
  user_id     uuid,
  user_name   text,
  role        text,
  created_at  timestamptz not null default now()
);
create index if not exists usage_logs_campus_time_idx on public.usage_logs (campus_id, created_at);
create index if not exists usage_logs_time_idx on public.usage_logs (created_at);
